server:
  port: 8080
  
logging:
  level:
    root: info
    web: debug
    org.springframework.web.servlet.mvc: trace
    com.tnr.scgcxx.dao: debug

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/prjdb?characterEncoding=UTF-8&useUnicode=true
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
#时区设置
    time-zone: Asia/Shanghai 
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.tnr.scgcxx.model
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
shiro:
  loginUrl: /loginTo
  successUrl: /successTo
  unauthorizedUrl: /unauthorizedTo
    