server:
  port: 8080
  
logging:
  level:
    root: info
    web: debug
    org.springframework.web.servlet.mvc: trace
    org.springframework.cache: trace
    com.tnr.scgcxx.dao: debug
    com.tnr.scgcxx.shiro.ShiroConfign: debug
    
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/prjdb?characterEncoding=UTF-8&useUnicode=true
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
#时区设置
    time-zone: Asia/Shanghai 
  redis: 
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis: 
      pool: 
        max-idle: 100
        max-wait: -1
        min-idle: 2
    timeout: 15000
    
  cache: 
    type: redis
    redis: 
      time-to-live: 6000000
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.tnr.scgcxx.model
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
shiro:
  loginUrl: /loginTo
  successUrl: /successTo
  unauthorizedUrl: /unauthorizedTo
    