server:
  port: 80
  
logging:
  lever:
    root: info
    web: debug
    org.springframework.web.servlet.mvc: trace
    com.tnr.scgcxx.dao: debug

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/prjdb
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.tnr.scgcxx.model
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
    